### ISSUE TITLE
grep error with spss_ascii_reader()

### ISSUE THREAD

**Issue by dwiwad** [jacobkap/asciiSetupReader#5]
Please briefly describe your problem and what output you expect. If you have a question, please don't use this form. Instead, ask on <https://stackoverflow.com/> or <https://community.rstudio.com/>.

Please include a minimal reproducible example (AKA a reprex). If you've never heard of a [reprex](http://reprex.tidyverse.org/) before, start by reading <https://www.tidyverse.org/help/#reprex>.

---

Hi Jacob, 

I'm attempting to use the spss_ascii_reader function on some data from the PSID. Particularly, the 2016 well-being and daily life survey (https://simba.isr.umich.edu/VS/f.aspx). I've re-posted the data on my github for your ease here: https://github.com/dwiwad/well-being-and-daily-life/tree/master/WB2016

I've been using the WB2016.txt and WB2016.sps files (though I tried the sas version as well. I've also tried various iterations of code (i.e., just choosing certain columns), as well as both the CRAN and devtools versions of asciiSetupReader.

The basic code I am running is:

```r
d <- spss_ascii_reader(dataset_name = 'WB2016.txt', sps_name = 'WB2016.sps')
```
and the error I am gettinng is:

Error in grep2("^variable labels$", codebook):grep2("^value labels$|missing values|^execute$",  : 
  NA/NaN argument

Any help would be appreciated! Thank you!

**Comment by dwiwad** [comment]
I will note that I've attempted this on some other longitudinal data from the PSID as well, and I get the same issue.

**Comment by fkup** [comment]
I have a very similar error as @dwiwad. 

I'm using Brazilian administrative education data from INEP. Specifically, it's the school census data (Censo Escolar) from 2002, available at http://inep.gov.br/microdados (direct download available clicking on this link: http://download.inep.gov.br/microdados/micro_censo_escolar2002.zip)

My data file name is DADOS_CENSOESC.txt (unzipped) and my setup SAS/SPSS files are INPUT_SAS_CENSOESC.sas / INPUT_SPSS_CENSOESC.sps

I'm using the same code as @dwiwad.

The error I'm getting is:
Error in 1:(grep2("^DATA LIST", codebook) - 1) : argument of length 0

Thanks for your help!

**Comment by jacobkap** [comment]
Hi,

Sorry for the late response, I just got back from vacation. I will take a look at both of these issues in the next few days.

**Comment by dwiwad** [comment]
Hi Jacob,

Absolutely no rush! I ended up using spss to generate the data, but it's a bug you might be wanting to fix anyways! Please let me know if and when it gets sorted so I can minimize my use of SPSS as much as possible!

Dylan

**Comment by ozgupolat** [comment]
Hello there,
I have the exact same problem with @dwiwad 
When i try to use "asciiSetupReader::read_ascii_setup", i am getting the same error:
Error in grep2("^variable labels$", codebook):grep2("^value labels$|missing values|^execute$",  : 
  NA/NaN argument

**Comment by ozgupolat** [comment]
Hello there,
I have the exact same problem with @dwiwad, and also i am trying to Psid data too.
When i try to use asciiSetupReader::read_ascii_setup, or spss_ascii_reader, or sas_ascii_reader i am getting the same error:
Error in grep2("^variable labels$", codebook):grep2("^value labels$|missing values|^execute$",  : 
  NA/NaN argument

**Comment by ozgupolat** [comment]
Hello there,
I have the exact same problem with @dwiwad, and also i am using Psid data too.
When i try to use asciiSetupReader::read_ascii_setup, or spss_ascii_reader, or sas_ascii_reader i am getting the same error:
Error in grep2("^variable labels$", codebook):grep2("^value labels$|missing values|^execute$",  : 
  NA/NaN argument

**Comment by jacobkap** [comment]
@dwiwad Can you check the dev version of this package on your data? It should be fixed now.

@fkup Can you send me just the .sps or .sas file? The link you sent isn't working when I try to download.

@ozgupolat What files specifically aren't working? Can you check them on the dev version of this package?

**Comment by fkup** [comment]
Hi @jacobkap, the data file size is 2.16 Gb so I'm not sure I can send it to you. The .zip link/URL I gave you to download the raw .TXT data is working. What issue do you encounter if you click on the link? 

Here are the .sas and .sps files: 

[sas_spss_file_BrazilCensus.zip](https://github.com/jacobkap/asciiSetupReader/files/3244509/sas_spss_file_BrazilCensus.zip)

I was finally able to donwload and parse most of the .TXT files with the microdadosBrasil package from lucasmation. However, the 1998 school census is still not working well with his package, so I would definitely be happy to have some help with that file (i.e. if you're able to fix these bug I might be able to read it).

**Comment by ozgupolat** [comment]
@jacobkap Thank you for your reply. Maybe it is just me, but i got the same error in dev version too.
I uploaded a small sample data, if you want you can check by yourself:
https://send.firefox.com/download/742834f6b45be419/#3m6FNhASFfb8KGnPKzv1wg

By the way, i can use the function without any problem on your example and test data sets. Maybe it is about Psid files.
Thank you.

**Comment by jacobkap** [comment]
@fkup Thanks! Firefox was giving me a failure to download message so I think it was just due to the huge file size. I will work on those setup files today.

@ozgupolat Thanks I will work on this today. Some setup files are formatted slightly differently and that tends to break my package.

**Comment by dwiwad** [comment]
Thanks!! I'll test it out when I'm home tomorrow (travelling today).
--
Dylan Wiwad
PhD Candidate
Department of Psychology
Simon Fraser University
AQ 3135
email: dwiwad@sfu.ca

**Comment by jacobkap** [comment]
@fkup  Can you try the dev version now? You small sample data is working for me now.

**Comment by fkup** [comment]
Hi @jacobkap --

I'm still getting an error. Maybe it's related to how I'm using the functions?

Here's my code:

```
devtools::install_github("jacobkap/asciiSetupReader")
library('asciiSetupReader')
d <- sas_ascii_reader(dataset_name = "~/Dropbox/CensoEscolarBrasil/input/micro_censo_escolar2002/Dados/DADOS_CENSOESC.TXT", 
                      sas_name = "~/Dropbox/CensoEscolarBrasil/input/micro_censo_escolar2002/Inputs_SAS_SPSS/INPUT_SAS_CENSOESC.sas")
```

Here's my error message:
```
Error in grep2("^LABEL$", codebook):grep("^$", codebook)[grep("^$", codebook) >  : 
  argument of length 0
```

**Comment by jacobkap** [comment]
@fkup Yeah, the escolar data still has issues I'm working on. It only includes the default column name and spacing of the columns which is a different format than what I've seen before. The .sps file also starts the first column at 0 which is odd.

**Comment by fkup** [comment]
@jacobkap 

lucasmation has a package (called microdadosBrasil) that I used to import the school census data from 1999 to 2006 successfully (but he has a bug for the 1998 dataset, which I still need). 

Maybe his code could be helpful for fixing this bug?

PS: Thanks again for your work. If this project works out, I'm sure this package could become one of the most used R packages -- there's a **lot** of people with old SAS datasets and without SAS software!

**Comment by ozgupolat** [comment]
*Update
I have managed to make dev version work. But you must edit your data(txt) file's path which is inside your .sas file. Otherwise, no way to make your Psid files work, or you need to edit sas file in a different format.
Thank you @jacobkap for your effort, much appreciated.

**Comment by jacobkap** [comment]
@ozgupolat What do you mean? The data file path in the .sas file isn't used in this package.

**Comment by ozgupolat** [comment]
@jacobkap Yes, my mistake, data file path edit needed for another program that i used. I confuse it with your package.

By the way, i get warnings after importing files. Do you know what is wrong ? 
(Also i am adding sas format file which include proc format, and format labels into the sas file)
E.g. :
"In matrix(value_label_section, ncol = 2, byrow = TRUE) :
  data length [11] is not a sub-multiple or multiple of the number of rows [6]"

**Comment by jacobkap** [comment]
@ozgupolat That is an issue with the value labels. Can you try with the new dev version and if it still gives you that error send me the setup file.

@fkup escolar should work now for the .sps file on the new dev version of this package.

**Comment by ozgupolat** [comment]
@jacobkap Unfortunately it still gives the same warnings. Here are the setup files:
[Setup Files.zip](https://github.com/jacobkap/asciiSetupReader/files/3269084/Setup.Files.zip)

Thank you again.

**Comment by jacobkap** [comment]
@ozgupolat Are there .sps setup files as well?

**Comment by ozgupolat** [comment]
@jacobkap I am not working with spss, but sure, here they are:
[J260813.zip](https://github.com/jacobkap/asciiSetupReader/files/3269882/J260813.zip)
It include label format file separately.

**Comment by fkup** [comment]
Hi @jacobkap - I installed the dev version and I still get an error:

Here's my code:
```
d <- spss_ascii_reader(dataset_name =
"~/Dropbox/CensoEscolarBrasil/input/micro_censo_escolar2006/Dados/DADOS_CENSOESC.TXT", 
sps_name =
"~/Dropbox/CensoEscolarBrasil/input/micro_censo_escolar2006/INPUTS_SAS_SPSS/INPUT_SPSS_CENSOESC2006.sps")
```

Here's the error I get:
```
Error in read_tokens_(data, tokenizer, col_specs, col_names, locale_,  : 
  Begin offset (-2147483648) must be smaller than end offset (-2147483648)
In addition: Warning messages:
1: In get_column_spaces(setup, variables, codebook) :
  NAs introduced by coercion
2: In get_column_spaces(setup, variables, codebook) :
  NAs introduced by coercion
```

**Comment by jacobkap** [comment]
@fkup to confirm your data is from 2006 for "Censo Escolar" here http://inep.gov.br/microdados and uses the setup file here https://github.com/jacobkap/asciiSetupReader/blob/master/inst/testdata/escolar_2006_sps.zip? I am able to read the data (first 3 columns only since my laptop can't handle the full file) using the newest version. And the setup file parses without issue. 

@ozgupolat Can you try the newest version? The setup files parse correctly now.

**Comment by ozgupolat** [comment]
@jacobkap Thank you. Now reads the  J260813 sas files without any error.
But, i am working on another large file, and it give one single warning. Maybe it is not important, but what does it mean, am i doing something wrong ?
```
Warning message:
In matrix(value_label, ncol = 2, byrow = TRUE) :
  data length [45] is not a sub-multiple or multiple of the number of rows [23]
```

**Comment by ozgupolat** [comment]
@jacobkap Thank you. Now reads the  J260813 sas files without any error.
But, i am working on another large file, and it gives one single warning. Maybe it is not important, but what does it mean, am i doing something wrong ?
```
Warning message:
In matrix(value_label, ncol = 2, byrow = TRUE) :
  data length [45] is not a sub-multiple or multiple of the number of rows [23]
```

**Comment by jacobkap** [comment]
@ozgupolat  That means there is an issue with how the package reads in the value labels. If you send me that setup file (and any others you're working on) I'll add more tests and make sure my package reads them in right. Sorry about all these issues.

**Comment by ozgupolat** [comment]
@jacobkap Actually if i can find where is the problem, or what its source, i can modify sas file, or if the problem is neglectable, i can omit that labels/variables.
Here is the sas setup files [J260682.zip](https://github.com/jacobkap/asciiSetupReader/files/3291149/J260682.zip), but this time data file is larger, and probably will take more time to test unfortunately.
By the way, no need to be sorry. Your package worked out great for me, much appreciated.
Thank you for you all effort.

**Comment by jacobkap** [comment]
@ozgupolat  Thanks. The issue in value labels is usually a label being on more than one line such as ER34513F in the file you just sent. There the label for 0 has two sections in quotes which causes issues. Having ; also sometimes causes issues as that's how my code separates different columns in the value labels section.
